#!/usr/bin/env bash

PKG_MANAGER="sudo pacman -Sy --needed --noconfirm"

packages=(
    bat
    man-db
    man-pages
    fzf
    ripgrep
    tmux
    zsh
    nasm
    llvm
    clang
    gdb
    make
    cmake
    neovim
    git
    docker
    nmap
    gnu-netcat
)

echo "📦 Installing development packages..."
$PKG_MANAGER "${packages[@]}"

echo -e "\n🔍 Checking installation status..."
installed=$(pacman -Qq)

echo -e "\n🔍 Installation status:"
for pkg in "${packages[@]}"; do
    if rg -qw "^${pkg}$" <<< "$installed"; then
        printf "[✓] %-12s - Installed\n" "$pkg"
    else
        printf "[✗] %-12s - Failed\n" "$pkg"
    fi
done
