#!/usr/bin/env bash

PKG_MANAGER="sudo pacman -Sy --needed --noconfirm"

packages=(
    man-db
    man-pages
    websocat
    bat
    fzf
    tree
    ripgrep
    ffmpeg
    tmux
    zsh
    nasm
    llvm
    clang
    gdb
    make
    cmake
    ninja
    neovim
    git
    typst
    docker
    mesa
    nmap
    gnu-netcat
)

echo "📦 Installing development packages..."
$PKG_MANAGER "${packages[@]}"

echo -e "\n🔍 Checking installation status..."
installed=$(pacman -Qq)

echo -e "\n🔍 Installation status:"
for pkg in "${packages[@]}"; do
    if rg -qw "^${pkg}$" <<< "$installed"; then
        printf "[✓] %-12s - Installed\n" "$pkg"
    else
        printf "[✗] %-12s - Failed\n" "$pkg"
    fi
done
