#!/usr/bin/env bash

# Create four windows in the current tmux session
for i in {1..3}; do
    tmux new-window
done

# Rename the last two windows
tmux rename-window -t 3 "tests"
tmux rename-window -t 4 "debug"

# Switch back to the first window
tmux select-window -t 1
